services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nihilus\QueryBusInterface: '@Nihilus\QueryBus'
    Nihilus\CommandBusInterface: '@Nihilus\CommandBus'
    Nihilus\QueryHandlerResolverInterface: '@Wynd\CQRSBundle\Query\Resolver\ContainerQueryHandlerResolver'
    Nihilus\CommandHandlerResolverInterface: '@Wynd\CQRSBundle\Command\Resolver\ContainerCommandHandlerResolver'
    Nihilus\QueryMiddlewareResolverInterface: '@Wynd\CQRSBundle\Query\Resolver\ContainerQueryMiddlewareResolver'
    Nihilus\CommandMiddlewareResolverInterface: '@Wynd\CQRSBundle\Command\Resolver\ContainerCommandMiddlewareResolver'

    Nihilus\QueryBus: ~
    Nihilus\CommandBus: ~
    Wynd\CQRSBundle\Query\Resolver\ContainerQueryHandlerResolver: ~
    Wynd\CQRSBundle\Command\Resolver\ContainerCommandHandlerResolver: ~
    Wynd\CQRSBundle\Query\Resolver\ContainerQueryMiddlewareResolver: ~
    Wynd\CQRSBundle\Command\Resolver\ContainerCommandMiddlewareResolver: ~

    Wynd\CQRSBundle\Console\DebugCommand:
        arguments:
            $queryNames: '%wynd.cqrs.models.query%'
            $commandNames: '%wynd.cqrs.models.command%'