#!/usr/bin/env php
<?php

namespace Nihilus\CQRSBundle\Tests\App;

require_once __DIR__ . '/../../vendor/autoload.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new MicroKernel('dev', true);
$application = new Application($kernel);
$application->run();